### ISSUE TITLE
Rethink Labs

### ISSUE THREAD

**Issue by ctreatma** [equinix-labs/terraform-equinix-labs#47]
I think we should reconsider having the terraform-equinix-labs repo, or at least reiterate the goals it aims to achieve and consider if there are alternatives that would better fit the experimental/educational aspect of equinix-labs repos.  IMO a benefit of equinix-labs modules is the ability to easily see the code and use it as a reference.  If I come to a module through the Labs repo, I have to dig through a couple layers of indirection before I finally figure out where to look for the actual code I'm interested in.  This could be improved slightly by using GitHub sources for modules instead of Terraform registry sources (e.g., source = "[github.com/equinix-labs/terraform-equinix-metal-eks-anywhere](http://github.com/equinix-labs/terraform-equinix-metal-eks-anywhere)" instead of source = "equinix-labs/metal-eks-anywhere/equinix"), but I still have to go from Labs example => Labs main module => Labs submodule just to find that source attribution.

In addition, using this repo as a landing place for our modules forces us to implement those modules in a way that is perhaps undesirable.  This repo uses `count` to dynamically select which modules are enabled for a given run of `terraform plan/apply`. Modules [cannot be used with `count` if they include explicit provider configuration](https://developer.hashicorp.com/terraform/language/modules/develop/providers#legacy-shared-modules-with-provider-configurations), but [our template repo creates modules with explicit provider configuration](https://github.com/equinix-labs/terraform-equinix-template/blob/main/main.tf#L27-L29).  This makes it easier to develop and try out the modules that are created from the template: just set up your var file and go.  If we change the template and/or our modules to remove explicit configuration, then we have to use `examples` to run the module, which again adds indirection when someone is trying to understand what the code does and why.

**Comment by displague** [comment]
At the heart of this is the benefit, or perceived benefit, of Terraform modules. Who is the audience of the module, how will they use it? Who will build and maintain the module? How and where will it be reused?

Hashicorp has recommendations and suggestions that include:
- root module is required and opinionated [ref](https://developer.hashicorp.com/terraform/language/modules/develop/structure#:~:text=Root%20module.%20This%20is%20the%20only%20required%20element)
- don't modularize a single resource, just use the resource [ref](https://developer.hashicorp.com/terraform/language/modules/develop#when-to-write-a-module
)
- keep providers out of modules [ref](https://developer.hashicorp.com/terraform/language/modules/develop/providers)
- don't nest modules, keep them composable for reuse [ref](https://developer.hashicorp.com/terraform/language/modules/develop/composition)
- HCP "No-Code" Modules (a newer concept) require provider blocks in the root module [ref](https://developer.hashicorp.com/terraform/cloud-docs/no-code-provisioning/module-design
)

IMHO, this lends itself towards:
- modules/:
    - every chunk of reusable resources defining their own composable interface, dependent on external providers and inputs
- root:
    - the default, no-code, opinionated consumer of the modules with a ready-to-use provider block
- examples/:
    - alternative configuration to the defaults in the root module, and/or examples of the root configuration with additional setup to demonstrate. 
    - This would duplicate, not depend on the root module. 
    - Like the root module, would be dependent on modules/. 
    - Includes a provider block.

I recognize that my understanding of module best-practices has shifted after this round of reviewing Hashicorp documentation.

**Comment by cprivitere** [comment]
Does this mean the root module of equinix-labs has a giant provider block to emcompass all the possible providers used by the modules/ ?

**Comment by ocobles** [comment]
What is the actual likelihood of an organization exclusively for this purpose, like https://github.com/terraform-aws-modules
